### ISSUE TITLE
[タスク] 必要なパッケージの追加

### ISSUE THREAD

**Issue by p238049y** [p238049y/beer-collection-app#3]
### 目的
* 今後の開発に必要なものをあらかじめ準備しておくため

### 方針
* 以下のパッケージを追加する

```yaml
  # CupertinoIconsのアイコンを使うため
  cupertino_icons: ^1.0.2

  # OSS (https://github.com/microsoft/fluentui-system-icons)
  # fluentuiのアイコンを使うため
  fluentui_icons: ^1.0.0

  # 選択ダイアログを出すため
  flutter_picker: ^2.0.1

  # 多言語対応に備えるため
  intl: ^0.17.0

  # 状態管理を行うため
  provider: ^6.0.3

  # ローカルDBを実装するため
  sqflite: ^2.0.2

  # スライドスクロールを使用するため
  flutter_slidable: ^2.0.0

  # widget間に隙間を作るため
  get:
  gap: ^2.0.0
```
